comp: 0                                                                       # VAR ------------------------------ true or false
save: 1                                                                       # VAR ------------------------------ true or false
plot: 0                                                                       # VAR ------------------------------ true or false
inp: 0                                                                        # VAR ------------------------------ true or false
re_evaluate: 0                                                                # VAR ------------------------------ true or false
N_sims: 1                                                                     # VAR ------------------------------ int(\geq 1)

ALL: 1                                                                        # VAR ------------------------------ true or false
COST: 0                                                                       # VAR ------------------------------ true or false
SNR: 0                                                                        # set
FIND: 0                                                                       # VAR ------------------------------ true or false
