
model: "2W"                                                                 # VAR ------------------------------ [2W, W2, zero, Gaussian]
gamma: 0.5                                                                  # set
fixGamma: 1                                                                 # set | may be var (true or false)
Sigma_nom: [[1.0, 0.0], [0.0, 1.0]]                                         # set
var: 1                                                                      # set
percent: 1.00                                                               # VAR ------------------------------ \in {0, 1}
